# Generated by Django 4.2.5 on 2023-09-24 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=100)),
                ('params_1', models.CharField(max_length=50)),
                ('params_2', models.CharField(max_length=50)),
                ('params_3', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=100)),
                ('params_1', models.CharField(max_length=50)),
                ('params_2', models.CharField(max_length=50)),
                ('params_3', models.CharField(max_length=50)),
            ],
        ),
    ]
