# Generated by Django 4.2.5 on 2023-09-25 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colab', '0002_businesses_alter_groups_reason_alter_teams_reason'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businesses',
            name='params_1',
        ),
        migrations.RemoveField(
            model_name='businesses',
            name='params_2',
        ),
        migrations.RemoveField(
            model_name='businesses',
            name='params_3',
        ),
        migrations.RemoveField(
            model_name='businesses',
            name='reason',
        ),
        migrations.RemoveField(
            model_name='groups',
            name='params_1',
        ),
        migrations.RemoveField(
            model_name='groups',
            name='params_2',
        ),
        migrations.RemoveField(
            model_name='groups',
            name='params_3',
        ),
        migrations.RemoveField(
            model_name='groups',
            name='reason',
        ),
        migrations.RemoveField(
            model_name='teams',
            name='params_1',
        ),
        migrations.RemoveField(
            model_name='teams',
            name='params_2',
        ),
        migrations.RemoveField(
            model_name='teams',
            name='params_3',
        ),
        migrations.RemoveField(
            model_name='teams',
            name='reason',
        ),
        migrations.AddField(
            model_name='businesses',
            name='description',
            field=models.TextField(default='<django.db.models.fields.CharField> a brand new startup! We try to supply the best of services.'),
        ),
        migrations.AddField(
            model_name='businesses',
            name='key',
            field=models.CharField(default=41913897, max_length=8),
        ),
        migrations.AddField(
            model_name='businesses',
            name='name',
            field=models.CharField(default='Testing', max_length=30),
        ),
        migrations.AddField(
            model_name='groups',
            name='description',
            field=models.TextField(default='<django.db.models.fields.CharField> a brand new startup! We try to supply the best of services.'),
        ),
        migrations.AddField(
            model_name='groups',
            name='key',
            field=models.CharField(default=41913897, max_length=8),
        ),
        migrations.AddField(
            model_name='groups',
            name='name',
            field=models.CharField(default='Testing', max_length=30),
        ),
        migrations.AddField(
            model_name='teams',
            name='description',
            field=models.TextField(default='<django.db.models.fields.CharField> a brand new startup! We try to supply the best of services.'),
        ),
        migrations.AddField(
            model_name='teams',
            name='key',
            field=models.CharField(default=41913897, max_length=8),
        ),
        migrations.AddField(
            model_name='teams',
            name='name',
            field=models.CharField(default='Testing', max_length=30),
        ),
    ]
