# Generated by Django 4.2.5 on 2023-09-25 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colab', '0003_remove_businesses_params_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesses',
            name='key',
            field=models.CharField(default=18208324, max_length=8),
        ),
        migrations.AlterField(
            model_name='groups',
            name='description',
            field=models.TextField(default='<django.db.models.fields.CharField> a brand new group! We try to supply the best of services.'),
        ),
        migrations.AlterField(
            model_name='groups',
            name='key',
            field=models.CharField(default=18208324, max_length=8),
        ),
        migrations.AlterField(
            model_name='groups',
            name='name',
            field=models.CharField(default='New Group here!', max_length=30),
        ),
        migrations.AlterField(
            model_name='teams',
            name='description',
            field=models.TextField(default='<django.db.models.fields.CharField> a brand new team! We try to supply the best of services.'),
        ),
        migrations.AlterField(
            model_name='teams',
            name='key',
            field=models.CharField(default=18208324, max_length=8),
        ),
        migrations.AlterField(
            model_name='teams',
            name='name',
            field=models.CharField(default='New Team here!', max_length=30),
        ),
    ]
