# Generated by Django 4.2.5 on 2023-09-25 00:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colab', '0004_alter_businesses_key_alter_groups_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesses',
            name='admin',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='groups',
            name='admin',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='teams',
            name='admin',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='businesses',
            name='key',
            field=models.IntegerField(default=62599027, validators=[django.core.validators.MaxValueValidator(8)]),
        ),
        migrations.AlterField(
            model_name='businesses',
            name='name',
            field=models.CharField(default='New company here!', max_length=30),
        ),
        migrations.AlterField(
            model_name='groups',
            name='key',
            field=models.IntegerField(default=62599027, validators=[django.core.validators.MaxValueValidator(8)]),
        ),
        migrations.AlterField(
            model_name='teams',
            name='key',
            field=models.IntegerField(default=62599027, validators=[django.core.validators.MaxValueValidator(8)]),
        ),
    ]
