# Generated by Django 4.2.5 on 2023-09-25 01:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colab', '0005_businesses_admin_groups_admin_teams_admin_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessesManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('members', models.JSONField()),
                ('max_members', models.IntegerField(default=10)),
                ('key', models.IntegerField(default=32063365, validators=[django.core.validators.MaxValueValidator(8)])),
            ],
        ),
        migrations.CreateModel(
            name='GroupsManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('members', models.JSONField()),
                ('max_members', models.IntegerField(default=10)),
                ('key', models.IntegerField(default=32063365, validators=[django.core.validators.MaxValueValidator(8)])),
            ],
        ),
        migrations.CreateModel(
            name='TeamsManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('members', models.JSONField()),
                ('max_members', models.IntegerField(default=10)),
                ('key', models.IntegerField(default=32063365, validators=[django.core.validators.MaxValueValidator(8)])),
            ],
        ),
        migrations.AlterField(
            model_name='businesses',
            name='key',
            field=models.IntegerField(default=32063365, validators=[django.core.validators.MaxValueValidator(8)]),
        ),
        migrations.AlterField(
            model_name='groups',
            name='key',
            field=models.IntegerField(default=32063365, validators=[django.core.validators.MaxValueValidator(8)]),
        ),
        migrations.AlterField(
            model_name='teams',
            name='key',
            field=models.IntegerField(default=32063365, validators=[django.core.validators.MaxValueValidator(8)]),
        ),
    ]
