# Generated by Django 4.2.5 on 2023-09-25 01:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colab', '0006_businessesmanager_groupsmanager_teamsmanager_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teams',
            name='fundraiser',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='businesses',
            name='key',
            field=models.IntegerField(default=64156287, validators=[django.core.validators.MaxValueValidator(8)]),
        ),
        migrations.AlterField(
            model_name='businessesmanager',
            name='key',
            field=models.IntegerField(default=64156287, validators=[django.core.validators.MaxValueValidator(8)]),
        ),
        migrations.AlterField(
            model_name='groups',
            name='key',
            field=models.IntegerField(default=64156287, validators=[django.core.validators.MaxValueValidator(8)]),
        ),
        migrations.AlterField(
            model_name='groupsmanager',
            name='key',
            field=models.IntegerField(default=64156287, validators=[django.core.validators.MaxValueValidator(8)]),
        ),
        migrations.AlterField(
            model_name='teams',
            name='key',
            field=models.IntegerField(default=64156287, validators=[django.core.validators.MaxValueValidator(8)]),
        ),
        migrations.AlterField(
            model_name='teamsmanager',
            name='key',
            field=models.IntegerField(default=64156287, validators=[django.core.validators.MaxValueValidator(8)]),
        ),
    ]
